---
- name: Clear previous validation results (start fresh)
  agnosticd_user_info:
    data:
      ocp_application_validation_results: []

- name: run ocp application validation tasks
  include_tasks: ./loop-validations.yml
  loop: "{{ ocp_application_validation_list }}"
  loop_control:
    loop_var: _login
    index_var: _c_index

